[project]
name = "ardent-comfyui"
description = "Created by Ardent Illumina"
version = "0.1.2"
license = { file = "LICENSE" }

[project.urls]
Repository = "https://github.com/ardentillumina/ardent-comfy"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "ardentillumina"
DisplayName = "Ardent Illumina"
# Icon = ""
